FROM php:7.2-fpm

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    zip \
    unzip \
    git \
    curl

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring pdo

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer global require hirak/prestissimo

# Node.js
RUN curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN apt-get install nodejs -y
RUN npm install npm@6.9.0 -g

COPY . /var/www/html
WORKDIR /var/www/html

RUN chown -R $USER:www-data storage
RUN chown -R $USER:www-data bootstrap/cache

RUN composer install --no-interaction
RUN npm install
RUN cp .env.example .env && php artisan key:generate

RUN chmod -R 777 storage
RUN chmod -R 777 bootstrap/cache
