FROM nginx

# dev
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
# prod
# COPY ./docker/nginx/default-prod.conf /etc/nginx/conf.d/default.conf

COPY . /var/www/html

WORKDIR /var/www/html