FROM nginx

COPY ./nginx-dev.conf /etc/nginx/nginx.conf
COPY ./default-dev.conf /etc/nginx/conf.d/default.conf

RUN touch /var/run/nginx.pid && \
    chown -R www-data:www-data /var/run/nginx.pid && \
    chown -R www-data:www-data /var/cache/nginx

USER www-data

VOLUME /var/www/html